name: Lint & UnitTest
on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
jobs:
  lint-and-unittest:
    name: Lint & UnitTest
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure git for private modules
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${ACCESS_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: UnitTest
        run: go test -v ./...
